#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DialogMode {
    CreateBoard,
    CreateCard,
    RenameBoard,
    ExportBoard,
    ExportAll,
    ImportBoard,
    SetCardPoints,
    SetCardPriority,
    SetMultipleCardsPriority,
    SetBranchPrefix,
    OrderCards,
    OrderBoards,
    CreateSprint,
    AssignCardToSprint,
    AssignMultipleCardsToSprint,
    CreateColumn,
    RenameColumn,
    DeleteColumnConfirm,
    DeleteBoardConfirm,
    SelectTaskListView,
    SetSprintPrefix,
    SetSprintCardPrefix,
    ConfirmSprintPrefixCollision,
    FilterOptions,
    ConflictResolution,
    ExternalChangeDetected,
    ManageParents,
    ManageChildren,
    CarryOverSprint,
    ExportBoards,
    ChooseStorageFile,
    DeletePermanentBoardConfirm,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AppMode {
    Normal,
    CardDetail,
    BoardDetail,
    SprintDetail,
    Search,
    ArchivedCardsView,
    ArchivedBoardsView,
    Settings,
    Help(Box<AppMode>),
    Dialog(DialogMode),
    ErrorLog,
}
