//! The V15 -> V16 card-prefix backfill.
//!
//! The only property that matters: every card's identifier is the same before
//! and after. A backfill that writes a *plausible* prefix silently renames
//! cards, which is the exact defect storing the prefix exists to prevent.

use kanban_persistence::{FormatVersion, PersistenceStore};
use kanban_persistence_json::migration::Migrator;
use kanban_persistence_json::JsonFileStore;
use serde_json::Value;
use tempfile::tempdir;

fn read_json(path: &std::path::Path) -> Value {
    serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap()
}

/// Each card's identifier under the OLD dynamic rule: sprint override, else
/// the board reached through the column, else "task". Computed independently
/// of the migration so it cannot inherit the migration's own mistake.
fn identifiers_before(env: &Value) -> Vec<(String, String)> {
    let d = &env["data"];
    let get = |k: &str| d[k].as_array().cloned().unwrap_or_default();
    let mut out: Vec<(String, String)> = get("cards")
        .iter()
        .map(|card| {
            let sprint_prefix = card["sprint_id"].as_str().and_then(|sid| {
                get("sprints")
                    .iter()
                    .find(|s| s["id"] == sid)
                    .and_then(|s| s["card_prefix"].as_str().map(str::to_string))
            });
            let board_prefix = card["column_id"].as_str().and_then(|cid| {
                get("columns")
                    .iter()
                    .find(|c| c["id"] == cid)
                    .and_then(|c| c["board_id"].as_str().map(str::to_string))
                    .and_then(|bid| {
                        get("boards")
                            .iter()
                            .find(|b| b["id"] == bid)
                            .and_then(|b| b["card_prefix"].as_str().map(str::to_string))
                    })
            });
            let prefix = sprint_prefix
                .or(board_prefix)
                .unwrap_or_else(|| "task".to_string())
                .to_lowercase();
            let number = card["card_number"].as_u64().unwrap_or(0);
            (
                card["id"].as_str().unwrap().to_string(),
                format!("{prefix}-{number}"),
            )
        })
        .collect();
    out.sort();
    out
}

/// Generated by a real `kanban` binary predating V16, carrying an explicit
/// board prefix, a board relying on the default, a genuine two-board default
/// collision, and a sprint `card_prefix` override.
#[tokio::test]
async fn test_v15_to_v16_preserves_every_cards_identifier() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("store.json");
    std::fs::write(&path, include_str!("fixtures/v14_real_binary.json")).unwrap();

    let before = identifiers_before(&read_json(&path));
    assert!(!before.is_empty(), "fixture must contain cards");

    Migrator::migrate(FormatVersion::V14, FormatVersion::MAX, &path)
        .await
        .expect("migration must succeed");

    let after = read_json(&path);
    assert_eq!(after["version"], 17);

    let cards = after["data"]["cards"].as_array().unwrap();

    // Identity is compared case-insensitively, because lookups are: `kan-5`
    // and `KAN-5` name the same card. What must not change is which NAMESPACE
    // and which NUMBER a card belongs to.
    let mut stamped: Vec<(String, String)> = cards
        .iter()
        .map(|c| {
            (
                c["id"].as_str().unwrap().to_string(),
                format!(
                    "{}-{}",
                    c["prefix"]
                        .as_str()
                        .expect("every card gets a prefix")
                        .to_lowercase(),
                    c["card_number"].as_u64().unwrap_or(0)
                ),
            )
        })
        .collect();
    stamped.sort();

    assert_eq!(
        stamped, before,
        "every card's identifier must resolve to the same namespace and number \
         before and after; a backfill that changes one has renamed a card"
    );

    // Casing is preserved too, and separately: it is what branch names render,
    // and lowercasing it would move every checked-out branch.
    let boards = after["data"]["boards"].as_array().unwrap();
    let columns = after["data"]["columns"].as_array().unwrap();
    let configured: Vec<&str> = boards
        .iter()
        .filter_map(|b| b["card_prefix"].as_str())
        .collect();
    assert!(
        configured.iter().any(|p| p.chars().any(char::is_uppercase)),
        "fixture must configure at least one upper-case prefix, or this proves nothing"
    );
    for card in cards {
        let board_prefix = card["column_id"].as_str().and_then(|cid| {
            columns
                .iter()
                .find(|c| c["id"] == cid)
                .and_then(|c| c["board_id"].as_str())
                .and_then(|bid| {
                    boards
                        .iter()
                        .find(|b| b["id"] == bid)
                        .and_then(|b| b["card_prefix"].as_str())
                })
        });
        // Only board-derived cards; a sprint override has its own casing.
        if card["sprint_id"].is_null() {
            if let Some(expected) = board_prefix {
                assert_eq!(
                    card["prefix"].as_str().unwrap(),
                    expected,
                    "the stamped prefix must keep the board's configured casing"
                );
            }
        }
    }
}

#[tokio::test]
async fn test_v15_to_v16_stamped_prefixes_survive_a_backend_flush() {
    use kanban_persistence::{snapshot_from_json_bytes, snapshot_to_json_bytes, StoreSnapshot};

    let dir = tempdir().unwrap();
    let path = dir.path().join("store.json");
    std::fs::write(&path, include_str!("fixtures/v14_real_binary.json")).unwrap();
    Migrator::migrate(FormatVersion::V14, FormatVersion::MAX, &path)
        .await
        .unwrap();
    let before = read_json(&path)["data"]["cards"].clone();

    let store = JsonFileStore::new(&path);
    let (loaded, metadata) = store.load().await.unwrap();
    let snapshot = snapshot_from_json_bytes(&loaded.data).unwrap();
    let data = snapshot_to_json_bytes(&snapshot).unwrap();
    store.save(StoreSnapshot { data, metadata }).await.unwrap();

    let after = read_json(&path)["data"]["cards"].clone();
    let prefixes = |v: &Value| -> Vec<String> {
        let mut p: Vec<String> = v
            .as_array()
            .unwrap()
            .iter()
            .map(|c| c["prefix"].as_str().unwrap_or("").to_string())
            .collect();
        p.sort();
        p
    };
    assert_eq!(
        prefixes(&after),
        prefixes(&before),
        "an ordinary save must not strip the stamped prefixes"
    );
}
